<a href="https://colab.research.google.com/github/naponite/data-science-bootcamp-8/blob/main/python/Essential_Python_for_Data_Analyst.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Essential Python for Data Analyst


- control flow + review function
- OOP
- try except block
- csv, json
- context manager
- requests, api
- basic web scraping
- intro to data science libraries (numpy, pandas)

In [ ]:

# if elif else
def grading(score):
  # docstrings
  """
  this function return grade for a student
  in UK
  """

  if score >= 70:
    return "Disctinction"
  elif score >= 60:
    return "Merit"
  elif score >= 50:
    return "Passed"
  else:
    return "Failed"

In [ ]:
grading(80)

'Disctinction'

In [ ]:
# for loop
nums = [1,2,3,4,5] ## => [2,4,6,8,10]

new_nums = [] # empty list

for num in nums:
  new_nums.append(num*2)

print(new_nums)


[2, 4, 6, 8, 10]


In [ ]:
## program to check odd/ even numbers
nums  = [35, 50, 22, 21, 28]


In [ ]:
# while loop
count = 0

while count < 5:
  print("hello")

In [ ]:
# get input from a user
def animal_guessing():
  set_animal = "hippo"
  answers = []
  while True:
    guess = input("Guess the animal: ")
    answers.append(guess)
    if guess == set_animal:
      print("Hooray! correct answer")
      print(f"Logs: {answers} ")
      break
    elif guess == "quit":
      print("See you next time.")
      break
    else:
      print("Nope! please try again.")



In [ ]:
animal_guessing()


Guess the animal: dog
Nope! please try again.
Guess the animal: cat
Nope! please try again.
Guess the animal: bird
Nope! please try again.
Guess the animal: aaa
Nope! please try again.
Guess the animal: owl
Nope! please try again.
Guess the animal: hippo
Hooray! correct answer
Logs: ['dog', 'cat', 'bird', 'aaa', 'owl', 'hippo'] 


In [ ]:
## OOP => Object Oriented Progamming


In [ ]:
## Dog
class Dog:
  # initialize
  def __init__(self,name, age, breed): # double _ is dunder  # self will refer to Dog
        self.name = name
        self.age = age
        self.breed = breed

  ## dog methods (function)
  def sit(self):
      print("I am sitting now.")

  def sleep(self):
    print("I'm sleeping now.")

  def get_older(self, year):
    self.age += year
    print(self.age)



In [ ]:
## create a new instance
dog1 = Dog("john", 7, "chihuahua")


In [ ]:
dog1.sit()


I am sitting now.


In [ ]:
dog1.sleep()

I'm sleeping now.


In [ ]:
dog1.get_older(5)

12


In [ ]:
class Apple:
  def __init__(self, size, price, color):
    self.size = size
    self.price = price
    self.color = color

apple1 = Apple("medium", 5, "red")

print(apple1.size, apple1.price, apple1.color)

medium 5 red


In [ ]:
import csv

In [ ]:
# open csv file using read mode
file = open("friend.csv", "r")

In [ ]:
# read content in this file
data = csv.reader(file)


In [ ]:
for row in data:
  print(row)

['id', 'name', 'age', 'company']
['1', 'toy', '30', 'Google']
['2', 'top', '31', 'Amazon']
['3', 'jane', '25', 'Microsoft']
['4', 'john', '28', 'Meta']
['5', 'anna', '29', 'Anaconda']


In [ ]:
# close file
file.close

<function TextIOWrapper.close()>

In [ ]:
# pandas
import pandas as pd

In [ ]:
pd.read_csv('friend')

In [ ]:
## context manager => with
## use to open data file

In [ ]:
# import csv or
from csv import reader  # if this method, we no need to type csv.reader
result = []

with open("friend.csv", "r") as file:
  #data = csv.reader(file)
  data = reader(file)
  for row in data:
    result.append(row)

result

[['id', 'name', 'age', 'company'],
 ['1', 'toy', '30', 'Google'],
 ['2', 'top', '31', 'Amazon'],
 ['3', 'jane', '25', 'Microsoft'],
 ['4', 'john', '28', 'Meta'],
 ['5', 'anna', '29', 'Anaconda']]

In [ ]:
## write mode
from csv import reader, writer
header = []

In [ ]:
## dict => json
import json
book = {
    "name": "How to be better at almost everthing",
    "year": 2018,
    "author": "Pat Flynn",
    "favorite": True

}

with open("book.json", "w") as file:
  json.dump(book, file)
  print("Create file successfully!")

Create file successfully!


In [ ]:
# API => Application Programming Interface
# Communication between two machines

# request-response
# simple example
import requests

url ="https://swapi.dev/api/people/9/"

resp= requests.get(url)

## if success, OK 200
print(f"CODE:{resp.status_code}")

## see information
resp.text


CODE:200


'{"name":"Biggs Darklighter","height":"183","mass":"84","hair_color":"black","skin_color":"light","eye_color":"brown","birth_year":"24BBY","gender":"male","homeworld":"https://swapi.dev/api/planets/1/","films":["https://swapi.dev/api/films/1/"],"species":[],"vehicles":[],"starships":["https://swapi.dev/api/starships/12/"],"created":"2014-12-10T15:59:50.509000Z","edited":"2014-12-20T21:17:50.323000Z","url":"https://swapi.dev/api/people/9/"}'

In [ ]:
## see information in json format
resp.json()
resp.json()["name"]

'Biggs Darklighter'

In [ ]:
# get API data for 5 names

import requests
import time

characters = []

for i in range(5):
    url = f"https://swapi.dev/api/people/{i+1}"
    resp= requests.get(url)
    if resp.status_code == 200:
      json_data = resp.json()
      characters.append(
          (json_data["name"],
          json_data["height"])    # this is used case for tuple (list also can use)
      )
    # break a second
    time.sleep(1)

    else:
      characters.append("error") # add error detector


print(characters)


[('Luke Skywalker', '172'), ('C-3PO', '167'), ('R2-D2', '96'), ('Darth Vader', '202'), ('Leia Organa', '150')]


In [ ]:
characters

[('Luke Skywalker', '172'),
 ('C-3PO', '167'),
 ('R2-D2', '96'),
 ('Darth Vader', '202'),
 ('Leia Organa', '150')]

In [ ]:
# web scraping
# install new library on google colab
# pip => package manager in Python

!pip install gazpacho

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for gazpacho: filename=gazpacho-1.1-py3-none-any.whl size=7461 sha256=8f1d5387c7b21af1b5e09e1aadb90522687515df559566c4f84f3e3902de5dad
  Stored in directory: /root/.cache/pip/wheels/9b/bf/9f/8c8849499462415fa5cdf0d9edb1103c189bdbece90c51488e
Successfully built gazpacho


In [ ]:
!pip list

Package                          Version
-------------------------------- ---------------------
absl-py                          1.4.0
aiohttp                          3.8.5
aiosignal                        1.3.1
alabaster                        0.7.13
albumentations                   1.3.1
altair                           4.2.2
annotated-types                  0.5.0
anyio                            3.7.1
appdirs                          1.4.4
argon2-cffi                      23.1.0
argon2-cffi-bindings             21.2.0
array-record                     0.4.1
arviz                            0.15.1
astropy                          5.3.2
astunparse                       1.6.3
async-timeout                    4.0.3
attrs                            23.1.0
audioread                        3.0.0
autograd                         1.6.2
Babel                            2.12.1
backcall                         0.2.0
beautifulsoup4                   4.11.2
bleach                           6.0.0


In [ ]:
## import function
from gazpacho import Soup
import requests

In [ ]:
# web sraping basic
url = "https://www.imdb.com/search/title/?groups=top_100&sort=user_rating,desc"

html = requests.get(url)
print(html) # check status code

<Response [200]>


In [ ]:
html.text

In [ ]:
imdb = Soup(html.text)
print(imdb)

In [ ]:
titles = imdb.find("h3", {"class": "lister-item-header"})
# the data collected in list data type

# basic cleaning method by for loop

"""
clean_titles = []


for title in titles:
  clean_titles.append(title.strip())
"""

# list comprehension to clean by one shot

clean_titles = [title.strip() for title in titles]

clean_titles

['1. The Shawshank Redemption (1994)',
 '2. The Godfather (1972)',
 '3. The Dark Knight (2008)',
 "4. Schindler's List (1993)",
 '5. The Godfather Part II (1974)',
 '6. The Lord of the Rings: The Return of the King (2003)',
 '7. 12 Angry Men (1957)',
 '8. Pulp Fiction (1994)',
 '9. Spider-Man: Across the Spider-Verse (2023)',
 '10. Inception (2010)',
 '11. The Lord of the Rings: The Fellowship of the Ring (2001)',
 '12. Fight Club (1999)',
 '13. Forrest Gump (1994)',
 '14. The Good, the Bad and the Ugly (1966)',
 '15. The Lord of the Rings: The Two Towers (2002)',
 '16. Interstellar (2014)',
 '17. Goodfellas (1990)',
 '18. The Matrix (1999)',
 "19. One Flew Over the Cuckoo's Nest (1975)",
 '20. Star Wars: Episode V - The Empire Strikes Back (1980)',
 '21. Oppenheimer (2023)',
 '22. Se7en (1995)',
 '23. The Silence of the Lambs (1991)',
 '24. Terminator 2: Judgment Day (1991)',
 '25. Saving Private Ryan (1998)',
 '26. The Green Mile (1999)',
 '27. Spirited Away (2001)',
 '28. Star Wars:

In [ ]:
# clean rating
ratings = imdb.find("div", {"class": "inline-block ratings-imdb-rating"})


# list comprehension to clean by one shot
# use float to convert string to number
clean_ratings = [float(rating.strip()) for rating in ratings]

clean_ratings

[9.3,
 9.2,
 9.0,
 9.0,
 9.0,
 9.0,
 9.0,
 8.9,
 8.8,
 8.8,
 8.8,
 8.8,
 8.8,
 8.8,
 8.8,
 8.7,
 8.7,
 8.7,
 8.7,
 8.7,
 8.6,
 8.6,
 8.6,
 8.6,
 8.6,
 8.6,
 8.6,
 8.6,
 8.6,
 8.6,
 8.6,
 8.6,
 8.6,
 8.5,
 8.5,
 8.5,
 8.5,
 8.5,
 8.5,
 8.5,
 8.5,
 8.5,
 8.5,
 8.5,
 8.5,
 8.5,
 8.5,
 8.5,
 8.5,
 8.5]

In [ ]:
# create dataframe
import pandas as pd
movie_database = pd.DataFrame(data = {
    "title" : clean_titles,
    "rating" : clean_ratings

})

# view first five rows
movie_database.head()

title  rating
0  1. The Shawshank Redemption (1994)     9.3
1             2. The Godfather (1972)     9.2
2           3. The Dark Knight (2008)     9.0
3          4. Schindler's List (1993)     9.0
4     5. The Godfather Part II (1974)     9.0

In [ ]:
# numerical python
# very fast

In [ ]:
import numpy as np

nums = [1,2,3,4,5]

In [ ]:
[num*2 for num in nums]

[2, 4, 6, 8, 10]

In [ ]:
nums = np.array(nums)
print(nums*2)
print(nums/2)
print(nums+5)
print(nums-5)

[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]
[ 6  7  8  9 10]
[-4 -3 -2 -1  0]


In [ ]:
# statistics calculation
print(nums.min())
print(nums.max())
print(nums.mean())
print(nums.std())

# median has only function form (no method form as above)
print(np.median(nums))

1
5
3.0
1.4142135623730951
3.0


In [ ]:
np.arange(10) # same as range in native python "range(10)""

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(10) +1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.linspace(0,10, num=20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [ ]:
n2 = np.array([
    [1,2],
    [3,4]

])

print(n2, type(n2))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [ ]:
## matrix * matrix
## .dot notation
m1 = np.array([[1,2],[5,5]])
m2 = np.array([[4,2],[1,2]])

np.dot(m1,m2)

array([[ 6,  6],
       [25, 20]])

# pandas library

In [ ]:
# import pandas
# manage dataframe
import pandas as pd

# read data from csv file

url = "https://gist.githubusercontent.com/seankross/a412dfbd88b3db70b74b/raw/5f23f993cd87c283ce766e7ac6b329ee7cc2e1d1/mtcars.csv"

mtcars = pd.read_csv(url)

In [ ]:
# view first five rows
mtcars.head()

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [ ]:
# view data frame size
mtcars.shape

(32, 12)

In [ ]:
# view summary data frame
mtcars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   model   32 non-null     object 
 1   mpg     32 non-null     float64
 2   cyl     32 non-null     int64  
 3   disp    32 non-null     float64
 4   hp      32 non-null     int64  
 5   drat    32 non-null     float64
 6   wt      32 non-null     float64
 7   qsec    32 non-null     float64
 8   vs      32 non-null     int64  
 9   am      32 non-null     int64  
 10  gear    32 non-null     int64  
 11  carb    32 non-null     int64  
dtypes: float64(5), int64(6), object(1)
memory usage: 3.1+ KB


In [ ]:
# subset of data frame
mtcars["mpg"]
mtcars[["mpg", "model","hp"]].head()

mpg              model   hp
0  21.0          Mazda RX4  110
1  21.0      Mazda RX4 Wag  110
2  22.8         Datsun 710   93
3  21.4     Hornet 4 Drive  110
4  18.7  Hornet Sportabout  175

In [ ]:
# filter
mtcars["mpg"] > 30  # result will show in boolean
mtcars [ mtcars["mpg"] > 30 ]  # to display dataframe correctly

model   mpg  cyl  disp   hp  drat     wt   qsec  vs  am  gear  \
17        Fiat 128  32.4    4  78.7   66  4.08  2.200  19.47   1   1     4   
18     Honda Civic  30.4    4  75.7   52  4.93  1.615  18.52   1   1     4   
19  Toyota Corolla  33.9    4  71.1   65  4.22  1.835  19.90   1   1     4   
27    Lotus Europa  30.4    4  95.1  113  3.77  1.513  16.90   1   1     5   

    carb  
17     1  
18     2  
19     1  
27     2

In [ ]:
# filter for multiple condition
mtcars [ (mtcars["mpg"] > 30) & (mtcars["hp"] > 100) ]

model   mpg  cyl  disp   hp  drat     wt  qsec  vs  am  gear  carb
27  Lotus Europa  30.4    4  95.1  113  3.77  1.513  16.9   1   1     5     2

In [ ]:
# pandas .query()
# condition used to filter dataframe
mtcars.query(" mpg > 30 and hp > 100")

model   mpg  cyl  disp   hp  drat     wt  qsec  vs  am  gear  carb
27  Lotus Europa  30.4    4  95.1  113  3.77  1.513  16.9   1   1     5     2

In [ ]:
# aggregate + group by
# read data from store.csv
import pandas as pd
store = pd.read_csv("store.csv")


In [ ]:
store.shape

(9161, 21)

In [ ]:
store.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9161 entries, 0 to 9160
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Row ID         9161 non-null   int64  
 1   Order ID       9161 non-null   object 
 2   Order Date     9160 non-null   object 
 3   Ship Date      9160 non-null   object 
 4   Ship Mode      9160 non-null   object 
 5   Customer ID    9160 non-null   object 
 6   Customer Name  9160 non-null   object 
 7   Segment        9160 non-null   object 
 8   Country        9160 non-null   object 
 9   City           9160 non-null   object 
 10  State          9160 non-null   object 
 11  Postal Code    9160 non-null   float64
 12  Region         9160 non-null   object 
 13  Product ID     9160 non-null   object 
 14  Category       9160 non-null   object 
 15  Sub-Category   9160 non-null   object 
 16  Product Name   9160 non-null   object 
 17  Sales          9160 non-null   float64
 18  Quantity

In [ ]:
store.columns # check column name to clean

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [ ]:
col_names = list(store.columns)
clean_col_names = [col.lower().replace(" ","_").replace("-","_") for col in col_names]
store.columns = clean_col_names

In [ ]:
store.head()

row_id        order_id  order_date   ship_date       ship_mode customer_id  \
0       1  CA-2016-152156   11/8/2016  11/11/2016    Second Class    CG-12520   
1       2  CA-2016-152156   11/8/2016  11/11/2016    Second Class    CG-12520   
2       3  CA-2016-138688   6/12/2016   6/16/2016    Second Class    DV-13045   
3       4  US-2015-108966  10/11/2015  10/18/2015  Standard Class    SO-20335   
4       5  US-2015-108966  10/11/2015  10/18/2015  Standard Class    SO-20335   

     customer_name    segment        country             city  ...  \
0      Claire Gute   Consumer  United States        Henderson  ...   
1      Claire Gute   Consumer  United States        Henderson  ...   
2  Darrin Van Huff  Corporate  United States      Los Angeles  ...   
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...   
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...   

  postal_code  region       product_id         category sub_category  \
0       42420   South  FUR-BO-10001798        Furniture    Bookcases   
1       42420   South  FUR-CH-10000454        Furniture       Chairs   
2       90036    West  OFF-LA-10000240  Office Supplies       Labels   
3       33311   South  FUR-TA-10000577        Furniture       Tables   
4       33311   South  OFF-ST-10000760  Office Supplies      Storage   

                                        product_name     sales  quantity  \
0                  Bush Somerset Collection Bookcase  261.9600         2   
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3   
2  Self-Adhesive Address Labels for Typewriters b...   14.6200         2   
3      Bretford CR4500 Series Slim Rectangular Table  957.5775         5   
4                     Eldon Fold 'N Roll Cart System   22.3680         2   

   discount    profit  
0      0.00   41.9136  
1      0.00  219.5820  
2      0.00    6.8714  
3      0.45 -383.0310  
4      0.20    2.5164  

[5 rows x 21 columns]

In [ ]:
# aggregate sum
store["sales"].sum()

2297200.8603000003

In [ ]:
# aggregate + groupby
# group by region
store.groupby("region")["sales"].sum()


# refer R programming concept

# store %>% groupby(region) %>% summarise(sum(sales))


region
Central    501239.8908
East       678781.2400
South      391721.9050
West       725457.8245
Name: sales, dtype: float64

In [ ]:
# group by segment
store.groupby("segment")["sales"].sum()

segment
Consumer       1.161401e+06
Corporate      7.061464e+05
Home Office    4.296531e+05
Name: sales, dtype: float64

In [ ]:
# group by with multiple keys
result = store.groupby(["segment", "category"])["sales"].sum().reset_index()

In [ ]:
# save to csv file
result.to_csv("agg_data.csv")

In [ ]:
# multiple aggregated columns
store.groupby("segment")["sales"].\
    agg(["sum", "mean", "std"]).\
    reset_index()

segment           sum        mean         std
0     Consumer  1.161401e+06  223.733644  585.516175
1    Corporate  7.061464e+05  233.823300  599.410408
2  Home Office  4.296531e+05  240.972041  755.516379

In [ ]:
# read data from sql database